{% set name = "lucit-licensing-python" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - pip
  run:    
    - python
    - cython
    - requests
    - simplejson

channels:
  - lucit
  - conda-forge
  - default

dependencies:
  - anaconda-client
  - conda-build

test:
  imports:
    - lucit_licensing_python
  commands:
    - pip check
  requires:
    - pip

about:
  summary: LUCIT Licensing Client Module
  description: |
    {% block description %}
    {% include 'README.md' %}
    {% endblock %}
  dev_url: https://github.com/LUCIT-Systems-and-Development/lucit-licensing-python
  doc_url: https://lucit-licensing-python.docs.lucit.tech
  home: https://www.lucit.tech/lucit-licensing-python.html
  license: LSOSL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oliver-zehentleitner
