name: Build and Publish
on:
  workflow_dispatch:
jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get package name from setup.py
        run: echo "PACKAGE_NAME=$(python setup.py --name)" >> $GITHUB_ENV
      - name: Get version from setup.py
        run: echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
  upload_pypi:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Please read the CHANGELOG for further information: 
            https://github.com/LUCIT-Systems-and-Development/lucit-licensing-python/blob/main/CHANGELOG.md
          files: release_${{ matrix.release_suffix }}
          tag_name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}
