name: Build and Publish Anaconda

on:
  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Build conda on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install Conda Tools
        run: |
          conda install -c conda-forge conda-build
          conda install conda-verify
          conda install -c anaconda anaconda-client

      - name: Configure PATH
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install Python Tools
        run: |
          pip install setuptools wheel --upgrade       

      - name: Set up Xcode (only on macOS)
        if: runner.os == 'macOS'
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version
          clang --version

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: .
          python-version: ${{ matrix.python-version }}
          overwrite: true
          user: lucit
          label: main
          token: ${{ secrets.ANACONDA_API_TOKEN }}
