name: Build and Publish Anaconda

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  conda_deployment_with_new_tag:
    name: Build conda on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-20.04, windows-2019, macos-11]
        os: [macos-11]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
          - os: windows-2019
            python-version: "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install Conda Tools
        run: |
          conda install -c conda-forge conda-build
          conda install conda-verify
          conda install -c anaconda anaconda-client

      - name: Install Python Tools
        run: |
          pip install setuptools wheel --upgrade       

      - name: Install macOS SDK (only on macOS)
        if: runner.os == 'macOS'
        run: |
          sudo mkdir -p /opt/MacOSX10.10.sdk
          sudo curl -L https://objects.githubusercontent.com/github-production-release-asset-2e65be/13597203/4880c500-ac28-11eb-82cd-b7931076ec6d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231113T182547Z&X-Amz-Expires=300&X-Amz-Signature=ab9ffcee7b102953170f53b28c44268ce3f847577318f6b26a361ca542948340&X-Amz-SignedHeaders=host&actor_id=47597331&key_id=0&repo_id=13597203&response-content-disposition=attachment%3B%20filename%3DMacOSX10.10.sdk.tar.xz&response-content-type=application%2Foctet-stream | sudo tar -xzf - -C /opt/MacOSX10.10.sdk

      - name: Set CONDA_BUILD_SYSROOT (only on macOS)
        if: runner.os == 'macOS'
        run: |
          echo "CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk # [osx]" > conda_build_config.yaml

      - name: Overview Build Tools (only on macOS)
        if: runner.os == 'macOS'
        run: |
          echo "xcodebuild -version"
          xcodebuild -version
          echo "clang --version"
          clang --version
          echo "which clang"
          which clang
          echo "xcrun --sdk macosx --show-sdk-path"
          xcrun --sdk macosx --show-sdk-path
          echo "xcrun --sdk macosx --show-sdk-version"
          xcrun --sdk macosx --show-sdk-version
          echo "which -a ld"
          which -a ld

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: .
          python-version: ${{ matrix.python-version }}
          overwrite: true
          user: lucit
          label: main
          token: ${{ secrets.ANACONDA_API_TOKEN }}
