name: Unittests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unittests
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls
    - name: Run Unittest
      env:
        LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
        LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source lucit_licensing_python unittest_lucit_licensing_python.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        name: codecov-umbrella
        verbose: true
